AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  sam-app
  
Globals:
  Function:
    Timeout: 10

Resources:
  CreateProductFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: products/
      Handler: handlers/create-product.lambdaHandler
      Runtime: nodejs24.x
      Architectures:
        - x86_64
      Policies: 
        - DynamoDBCrudPolicy:
            TableName: !Ref ProductsTable
      Environment:
        Variables:
          PRODUCTS_TABLE: !Ref ProductsTable
      Events:
        CreateProduct:
          Type: Api
          Properties:
            Path: /products
            Method: post
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: "es2020"
        Sourcemap: true
        EntryPoints: 
        - handlers/create-product.ts

  GetAllProductsFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: products/
      Handler: handlers/get-all-products.lambdaHandler
      Runtime: nodejs24.x
      Architectures:
        - x86_64
      Policies: 
        - DynamoDBCrudPolicy:
            TableName: !Ref ProductsTable
      Environment:
        Variables:
          PRODUCTS_TABLE: !Ref ProductsTable
      Events:
        GetAllProducts:
          Type: Api
          Properties:
            Path: /products
            Method: get
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: "es2020"
        Sourcemap: true
        EntryPoints: 
        - handlers/get-all-products.ts

  DeleteProductFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: products/
      Handler: handlers/delete-product.lambdaHandler
      Runtime: nodejs24.x
      Architectures:
        - x86_64
      Policies: 
        - DynamoDBCrudPolicy:
            TableName: !Ref ProductsTable
      Environment:
        Variables:
          PRODUCTS_TABLE: !Ref ProductsTable
      Events:
        DeleteProduct:
          Type: Api
          Properties:
            Path: /products/{id}
            Method: delete
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: "es2020"
        Sourcemap: true
        EntryPoints: 
        - handlers/delete-product.ts

  UpdateProductFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: products/
      Handler: handlers/update-product.lambdaHandler
      Runtime: nodejs24.x
      Architectures:
        - x86_64
      Policies: 
        - DynamoDBCrudPolicy:
            TableName: !Ref ProductsTable
      Environment:
        Variables:
          PRODUCTS_TABLE: !Ref ProductsTable
      Events:
        UpdateProduct:
          Type: Api
          Properties:
            Path: /products/{id}
            Method: put
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: "es2020"
        Sourcemap: true
        EntryPoints: 
        - handlers/update-product.ts

  ProductsTable:
    Type: AWS::Serverless::SimpleTable
    Properties:
      PrimaryKey:
        Name: id
        Type: String

Outputs:
  ProductsApi:
    Description: "API Gateway endpoint URL for Prod stage"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.${AWS::URLSuffix}/Prod/products/"
